# Generated by Django 6.1.1 on 2026-09-17 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_packageitinerary'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='inclusions',
            field=models.TextField(blank=True, help_text='Enter each inclusion on a new line.'),
        ),
    ]
