# Generated by Django 6.1.1 on 2026-09-17 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='inclusions',
            field=models.TextField(blank=True, help_text='Enter each inclusion on a new line.'),
        ),
    ]
